universe   = vanilla
executable = /uscms/home/avendras/nobackup/HSCP/run_directories/ms-Rhadron_mstop_2000/output-configs/run_ms-Rhadron_mstop_2000__qcut80.sh
getenv     = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output     = /uscms/home/avendras/nobackup/HSCP/run_directories/ms-Rhadron_mstop_2000/text-logs/condor.ms-Rhadron_mstop_2000.qcut80.out
error      = /uscms/home/avendras/nobackup/HSCP/run_directories/ms-Rhadron_mstop_2000/text-logs/condor.ms-Rhadron_mstop_2000.qcut80.err
log        = /uscms/home/avendras/nobackup/HSCP/run_directories/ms-Rhadron_mstop_2000/text-logs/condor.ms-Rhadron_mstop_2000.qcut80.log
request_cpus   = 2
request_memory = 8000
+MaxRuntime    = 72000
queue
